name: Deploy Portfolio to S3 and CloudFront

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - deploy-frontend-yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # frontend environment variables
      - name: Create .env
        run: |
          echo "VITE_LINKEDIN=${{ secrets.VITE_LINKEDIN }}" >> frontend/.env
          echo "VITE_GITHUB=${{ secrets.VITE_GITHUB }}" >> frontend/.env
          echo "VITE_LEGO_REPO=${{ secrets.VITE_LEGO_REPO }}" >> frontend/.env
          echo "VITE_RAG_REPO=${{ secrets.VITE_RAG_REPO }}" >> frontend/.env
          echo "VITE_ML_REPO=${{ secrets.VITE_ML_REPO }}" >> frontend/.env
          echo "VITE_STUDIO_REPO=${{ secrets.VITE_STUDIO_REPO }}" >> frontend/.env
          echo "VITE_RAG_URL=${{ secrets.VITE_RAG_URL }}" >> frontend/.env
          echo "VITE_ML_URL=${{ secrets.VITE_ML_URL }}" >> frontend/.env
          echo "VITE_STUDIO_URL=${{ secrets.VITE_STUDIO_URL }}" >> frontend/.env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React
        working-directory: ./frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync ./frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"